### ISSUE TITLE
npm run serv fails.

### ISSUE THREAD

**Issue by shrinegl** [etienne-martin/crookie#3]
[npm-debug.log](https://github.com/etienne-martin/crookie/files/1679599/npm-debug.log)

**Comment by AlexBeauchemin** [comment]
Can you do a 
`npm --version`
and 
`node --version`

and tell me what the output for each is?

Also are you able to run the tasks individually? What errors do you get?

`npm run build`
followed by 
`node dist/index`

**Comment by shrinegl** [comment]
npm --version: 2.7.4
node --version: v0.12.2
npm install worked with a few warnings.
npm run build fails:
[npm-debug.log](https://github.com/etienne-martin/crookie/files/1680128/npm-debug.log)

**Comment by AlexBeauchemin** [comment]
The project is built for node > 6 , might have to adjust the typescript config to support older versions of node.

I'll play with it a little bit see if I can reproduce the problem and push a quick fix

**Comment by AlexBeauchemin** [comment]
Unfortunately, you will need to use the correct version of node to run the project. Supporting node < 1 would imply to downgrade a lot of dependencies we are using and refactor a lot of code. 

The easiest way to do that without having to change the node version in your environment is to install and use nvm (step 6 of the readme).

If on osx/linux: https://github.com/creationix/nvm
If on windows: https://github.com/coreybutler/nvm-windows

Once installed, you can do a `nvm install 6.10 && nvm use` in the project folder, redo a `npm install` and then you should be able to run the project.
